# Generated by Django 2.2.2 on 2019-07-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190708_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience3',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
